- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:      
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - "{{ lm_sensors_package }}"
      - lsof
      - mc    
      - net-tools
      - "{{ nfs_client_package }}"
      - "{{ rename_package }}"
      - rsync
      - sshfs # 	filesystem client based on SSH File Transfer Protocol
      - tree
      - traceroute
      - wget
      - zsh  # shell with lots of features
      - nfs-common