# roles/local/tasks/ssh_config.yml
---

- name: Ensure .ssh dir exists for bill
  become: yes
  file:
    path: "/home/bill/.ssh"
    state: directory
    mode: '0700'
    owner: "bill"
    group: "bill"
  tags: ssh_config

- name: Deploy aggregated SSH config for bill
  become: yes
  template:
    src: ssh_config.j2
    dest: "/home/bill/.ssh/config"
    mode: '0644'
    owner: "bill"
    group: "bill"
  tags: ssh_config
